version: '3.9'
services:
  qdrant:
    image: qdrant/qdrant:v1.11.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ev
      POSTGRES_PASSWORD: evpass
      POSTGRES_DB: ev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  qdrant_data:
  pgdata:
