GEMINI_API_KEY = AIzaSyDnjIP4f6YbpoP5UV_LOytEqavYvYeNX0Q

SUPABASE_URL = "https://cncecvcnnutocwtvijhu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuY2VjdmNubnV0b2N3dHZpamh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTcwMzMsImV4cCI6MjA3MTA3MzAzM30.esxp5Wn5wcBpPRkelPN0HAxtEnPxbFYskPqGbJciHyE"